#filename=config
[server]
    name = "grpc-todo-server"
    host = "localhost"
    port = 3000

[database]
    dbhost = "127.0.0.1"
    dbport = 3306
    database = "todo"
    dbuser = "user"
    dbpassword = "password"
